apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: U3VwZXJTZWNyZXRQYXNzd29yZDEyMzQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcpatients-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mvcpatients
  template:
    metadata:
      labels:
        app: mvcpatients
    spec:
      containers:
      - name: mvcpatients-container
        image: idjohnson/freshmvcapp:0.1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "12.34.56.78"
        - name: DB_NAME
          value: "patientsdb"
        - name: DB_USER
          value: "patientuser"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: mvcpatients-service
spec:
  selector:
    app: mvcpatients
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
